apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pd.csi.storage.gke.io
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/eng-district-390211/zones/europe-west2-b/disks/my-gce-pd-volume

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: pd.csi.storage.gke.io
